"""
Haze-Library Type Stubs
================================================================================

Type annotations for haze_library Rust extension module.
Provides IDE support for 225+ technical indicators.

Auto-generated from Rust source code.
"""

from typing import List, Optional, Tuple, Any

__version__: str
__author__: str


# ==============================================================================
# Volatility (8 functions)
# ==============================================================================

def py_atr(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_atr2_signals(high: List[float], low: List[float], close: List[float], volume: List[float], trend_length: Optional[int] = None, confirmation_threshold: Optional[float] = None, momentum_window: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_atr2_signals_ml(high: List[float], low: List[float], close: List[float], volume: List[float], rsi_period: Optional[int] = None, atr_period: Optional[int] = None, ridge_alpha: Optional[float] = None, momentum_window: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float], List[float]]: ...
def py_bollinger_bands(close: List[float], period: Optional[int] = None, std_multiplier: Optional[float] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_donchian_channel(high: List[float], low: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_keltner_channel(high: List[float], low: List[float], close: List[float], period: Optional[int] = None, atr_period: Optional[int] = None, multiplier: Optional[float] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_natr(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_true_range(high: List[float], low: List[float], close: List[float], drift: Optional[int] = None) -> List[float]: ...


# ==============================================================================
# Momentum (22 functions)
# ==============================================================================

def py_ai_momentum_index(close: List[float], k: Optional[int] = None, trend_length: Optional[int] = None, smooth: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_ai_momentum_index_ml(close: List[float], rsi_period: Optional[int] = None, smooth_period: Optional[int] = None, use_polynomial: Optional[bool] = None, lookback: Optional[int] = None, train_window: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float], List[float]]: ...
def py_apo(close: List[float], fast_period: Optional[int] = None, slow_period: Optional[int] = None) -> List[float]: ...
def py_awesome_oscillator(high: List[float], low: List[float], fast_period: Optional[int] = None, slow_period: Optional[int] = None) -> List[float]: ...
def py_cci(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_cmo(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_coppock(close: List[float], period1: Optional[int] = None, period2: Optional[int] = None, wma_period: Optional[int] = None) -> List[float]: ...
def py_dynamic_macd(open: List[float], high: List[float], low: List[float], close: List[float], fast_length: Optional[int] = None, slow_length: Optional[int] = None, signal_smooth: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float]]: ...
def py_fibonacci_pivots(high: float, low: float, close: float) -> Tuple[float, float, float, float, float, float, float]: ...
def py_fisher_transform(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_kdj(high: List[float], low: List[float], close: List[float], k_period: Optional[int] = None, d_period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_macd(close: List[float], fast_period: Optional[int] = None, slow_period: Optional[int] = None, signal_period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_mom(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_ppo(close: List[float], fast_period: Optional[int] = None, slow_period: Optional[int] = None) -> List[float]: ...
def py_roc(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_rsi(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_stochastic(high: List[float], low: List[float], close: List[float], k_period: Optional[int] = None, d_period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_stochrsi(close: List[float], rsi_period: Optional[int] = None, stoch_period: Optional[int] = None, k_period: Optional[int] = None, d_period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_three_outside(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_tsi(close: List[float], long_period: Optional[int] = None, short_period: Optional[int] = None, signal_period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_ultimate_oscillator(high: List[float], low: List[float], close: List[float], period1: Optional[int] = None, period2: Optional[int] = None, period3: Optional[int] = None) -> List[float]: ...
def py_williams_r(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...


# ==============================================================================
# Trend (15 functions)
# ==============================================================================

def py_adx(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_ai_supertrend(high: List[float], low: List[float], close: List[float], k: Optional[int] = None, n: Optional[int] = None, price_trend: Optional[int] = None, predict_trend: Optional[int] = None, st_length: Optional[int] = None, st_multiplier: Optional[float] = None) -> Tuple[List[float], List[float]]: ...
def py_ai_supertrend_ml(high: List[float], low: List[float], close: List[float], st_length: Optional[int] = None, st_multiplier: Optional[float] = None, model_type: Optional[str] = None, lookback: Optional[int] = None, train_window: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float], List[float]]: ...
def py_aroon(high: List[float], low: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_choppiness(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_dx(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_minus_di(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_plus_di(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_psar(high: List[float], low: List[float], close: List[float], af_init: Optional[float] = None, af_increment: Optional[float] = None, af_max: Optional[float] = None) -> Tuple[List[float], List[float]]: ...
def py_qstick(open: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_sar(high: List[float], low: List[float], acceleration: Optional[float] = None, maximum: Optional[float] = None) -> List[float]: ...
def py_sarext(high: List[float], low: List[float], start_value: Optional[float] = None, offset_on_reverse: Optional[float] = None, af_init_long: Optional[float] = None, af_long: Optional[float] = None, af_max_long: Optional[float] = None, af_init_short: Optional[float] = None, af_short: Optional[float] = None, af_max_short: Optional[float] = None) -> List[float]: ...
def py_supertrend(high: List[float], low: List[float], close: List[float], period: Optional[int] = None, multiplier: Optional[float] = None) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_vhf(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_vortex(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...


# ==============================================================================
# Volume (14 functions)
# ==============================================================================

def py_ad(high: List[float], low: List[float], close: List[float], volume: List[float]) -> List[float]: ...
def py_add(values1: List[float], values2: List[float]) -> List[float]: ...
def py_adosc(high: List[float], low: List[float], close: List[float], volume: List[float], fast_period: Optional[int] = None, slow_period: Optional[int] = None) -> List[float]: ...
def py_advance_block(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_cmf(high: List[float], low: List[float], close: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...
def py_eom(high: List[float], low: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...
def py_ladder_bottom(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_mfi(high: List[float], low: List[float], close: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...
def py_nvi(close: List[float], volume: List[float]) -> List[float]: ...
def py_obv(close: List[float], volume: List[float]) -> List[float]: ...
def py_pvi(close: List[float], volume: List[float]) -> List[float]: ...
def py_pvt(close: List[float], volume: List[float]) -> List[float]: ...
def py_volume_profile(high: List[float], low: List[float], close: List[float], volume: List[float], num_bins: Optional[int] = None) -> Tuple[List[float], List[float], float]: ...
def py_vwap(high: List[float], low: List[float], close: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...


# ==============================================================================
# Moving Averages (22 functions)
# ==============================================================================

def py_alma(values: List[float], period: Optional[int] = None, offset: Optional[float] = None, sigma: Optional[float] = None) -> List[float]: ...
def py_dema(values: List[float], period: int) -> List[float]: ...
def py_ema(values: List[float], period: int) -> List[float]: ...
def py_frama(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_hma(values: List[float], period: int) -> List[float]: ...
def py_kama(values: List[float], period: Optional[int] = None, fast_period: Optional[int] = None, slow_period: Optional[int] = None) -> List[float]: ...
def py_linreg_supply_demand_signals(high: List[float], low: List[float], close: List[float], volume: List[float], linreg_period: Optional[int] = None, tolerance: Optional[float] = None) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_mama(values: List[float], fast_limit: Optional[float] = None, slow_limit: Optional[float] = None) -> Tuple[List[float], List[float]]: ...
def py_midpoint(values: List[float], period: int) -> List[float]: ...
def py_midprice(high: List[float], low: List[float], period: int) -> List[float]: ...
def py_pwma(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_rma(values: List[float], period: int) -> List[float]: ...
def py_sinwma(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_sma(values: List[float], period: int) -> List[float]: ...
def py_swma(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_t3(values: List[float], period: Optional[int] = None, vfactor: Optional[float] = None) -> List[float]: ...
def py_tema(values: List[float], period: int) -> List[float]: ...
def py_trima(values: List[float], period: int) -> List[float]: ...
def py_vidya(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_vwma(close: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...
def py_wma(values: List[float], period: int) -> List[float]: ...
def py_zlma(values: List[float], period: int) -> List[float]: ...


# ==============================================================================
# Candlestick Patterns (54 functions)
# ==============================================================================

def py_abandoned_baby(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_bearish_engulfing(open: List[float], close: List[float]) -> List[float]: ...
def py_bearish_harami(open: List[float], close: List[float]) -> List[float]: ...
def py_belthold(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_breakaway(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_bullish_engulfing(open: List[float], close: List[float]) -> List[float]: ...
def py_bullish_harami(open: List[float], close: List[float]) -> List[float]: ...
def py_closing_marubozu(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_concealing_baby_swallow(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_counterattack(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_dark_cloud_cover(open: List[float], high: List[float], close: List[float]) -> List[float]: ...
def py_doji(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_doji_star(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_dragonfly_doji(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_evening_doji_star(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_evening_star(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_falling_three_methods(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_gap_sidesidewhite(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_gravestone_doji(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_hammer(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_hanging_man(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_harami_cross(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_highwave(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_hikkake(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_hikkake_mod(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_homing_pigeon(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_identical_three_crows(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_inneck(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_inverted_hammer(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_kicking(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_long_legged_doji(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_marubozu(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_matching_low(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_morning_doji_star(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_morning_star(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_onneck(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_piercing_pattern(open: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_rickshaw_man(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_rising_three_methods(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_separating_lines(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_shooting_star(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_spinning_top(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_stalled_pattern(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_stick_sandwich(open: List[float], high: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_takuri(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_three_black_crows(open: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_three_white_soldiers(open: List[float], high: List[float], close: List[float]) -> List[float]: ...
def py_thrusting(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_tristar(open: List[float], high: List[float], low: List[float], close: List[float], body_threshold: Optional[float] = None) -> List[float]: ...
def py_tweezers_bottom(open: List[float], low: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_tweezers_top(open: List[float], high: List[float], close: List[float], tolerance: Optional[float] = None) -> List[float]: ...
def py_unique_3_river(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_upside_gap_two_crows(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_xside_gap_3_methods(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...


# ==============================================================================
# Statistical (13 functions)
# ==============================================================================

def py_beta(asset_returns: List[float], benchmark_returns: List[float], period: int) -> List[float]: ...
def py_correl(values1: List[float], values2: List[float], period: int) -> List[float]: ...
def py_correlation(x: List[float], y: List[float], period: int) -> List[float]: ...
def py_covariance(x: List[float], y: List[float], period: int) -> List[float]: ...
def py_linear_regression(y_values: List[float], period: int) -> Tuple[List[float], List[float], List[float]]: ...
def py_linearreg(values: List[float], period: int) -> List[float]: ...
def py_linearreg_angle(values: List[float], period: int) -> List[float]: ...
def py_linearreg_intercept(values: List[float], period: int) -> List[float]: ...
def py_linearreg_slope(values: List[float], period: int) -> List[float]: ...
def py_standard_error(y_values: List[float], period: int) -> List[float]: ...
def py_tsf(values: List[float], period: int) -> List[float]: ...
def py_var(values: List[float], period: int) -> List[float]: ...
def py_zscore(values: List[float], period: int) -> List[float]: ...


# ==============================================================================
# Price Transform (4 functions)
# ==============================================================================

def py_avgprice(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_medprice(high: List[float], low: List[float]) -> List[float]: ...
def py_typprice(high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_wclprice(high: List[float], low: List[float], close: List[float]) -> List[float]: ...


# ==============================================================================
# Math Functions (29 functions)
# ==============================================================================

def py_abs(values: List[float]) -> List[float]: ...
def py_acos(values: List[float]) -> List[float]: ...
def py_asin(values: List[float]) -> List[float]: ...
def py_atan(values: List[float]) -> List[float]: ...
def py_ceil(values: List[float]) -> List[float]: ...
def py_cos(values: List[float]) -> List[float]: ...
def py_cosh(values: List[float]) -> List[float]: ...
def py_detect_divergence(price: List[float], indicator: List[float], lookback: Optional[int] = None, threshold: Optional[float] = None) -> Tuple[Any, List[float]]: ...
def py_div(values1: List[float], values2: List[float]) -> List[float]: ...
def py_exp(values: List[float]) -> List[float]: ...
def py_floor(values: List[float]) -> List[float]: ...
def py_ht_sine(values: List[float]) -> Tuple[List[float], List[float]]: ...
def py_ln(values: List[float]) -> List[float]: ...
def py_log10(values: List[float]) -> List[float]: ...
def py_max(values: List[float], period: int) -> List[float]: ...
def py_min(values: List[float], period: int) -> List[float]: ...
def py_minmax(values: List[float], period: int) -> Tuple[List[float], List[float]]: ...
def py_minmaxindex(values: List[float], period: int) -> Tuple[List[float], List[float]]: ...
def py_mult(values1: List[float], values2: List[float]) -> List[float]: ...
def py_percent_rank(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_sin(values: List[float]) -> List[float]: ...
def py_sinh(values: List[float]) -> List[float]: ...
def py_slope(values: List[float], period: Optional[int] = None) -> List[float]: ...
def py_sqrt(values: List[float]) -> List[float]: ...
def py_standard_pivots(high: float, low: float, close: float) -> Tuple[float, float, float, float, float, float, float]: ...
def py_sub(values1: List[float], values2: List[float]) -> List[float]: ...
def py_sum(values: List[float], period: int) -> List[float]: ...
def py_tan(values: List[float]) -> List[float]: ...
def py_tanh(values: List[float]) -> List[float]: ...


# ==============================================================================
# Fibonacci (2 functions)
# ==============================================================================

def py_fib_extension(start_price: float, end_price: float, retracement_price: float) -> Any: ...
def py_fib_retracement(start_price: float, end_price: float) -> Any: ...


# ==============================================================================
# Pivot Points (2 functions)
# ==============================================================================

def py_camarilla_pivots(high: float, low: float, close: float) -> Tuple[float, float, float, float, float, float, float, float, float]: ...
def py_pivot_buy_sell(high: List[float], low: List[float], close: List[float], lookback: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float], List[float], List[float], Any]: ...


# ==============================================================================
# Ichimoku (1 functions)
# ==============================================================================

def py_ichimoku_cloud(high: List[float], low: List[float], close: List[float], tenkan_period: Optional[int] = None, kijun_period: Optional[int] = None, senkou_b_period: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float], List[float]]: ...


# ==============================================================================
# Cycle (4 functions)
# ==============================================================================

def py_ht_dcperiod(values: List[float]) -> List[float]: ...
def py_ht_dcphase(values: List[float]) -> List[float]: ...
def py_ht_phasor(values: List[float]) -> Tuple[List[float], List[float]]: ...
def py_ht_trendmode(values: List[float]) -> List[float]: ...


# ==============================================================================
# ML/AI Indicators (5 functions)
# ==============================================================================

def py_breaker_block_signals(open: List[float], high: List[float], low: List[float], close: List[float], lookback: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_fvg_signals(high: List[float], low: List[float]) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_general_parameters_signals(high: List[float], low: List[float], close: List[float], ema_fast: Optional[int] = None, ema_slow: Optional[int] = None, atr_period: Optional[int] = None, grid_multiplier: Optional[float] = None) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_pd_array_signals(high: List[float], low: List[float], close: List[float], swing_lookback: Optional[int] = None) -> Tuple[List[float], List[float], List[float], List[float]]: ...
def py_volume_filter(volume: List[float], period: Optional[int] = None) -> Tuple[List[bool], List[float], List[bool]]: ...


# ==============================================================================
# Signal Functions (2 functions)
# ==============================================================================

def py_calculate_stops(entry_price: float, atr_value: float, is_long: bool, sl_multiplier: Optional[float] = None, tp_multiplier: Optional[float] = None) -> Tuple[float, float]: ...
def py_combine_signals(buy1: List[float], sell1: List[float], buy2: List[float], sell2: List[float], weight1: Optional[float] = None) -> Tuple[List[float], List[float]]: ...


# ==============================================================================
# Other (25 functions)
# ==============================================================================

def py_aberration(high: List[float], low: List[float], close: List[float], period: Optional[int] = None, atr_period: Optional[int] = None) -> List[float]: ...
def py_alligator(high: List[float], low: List[float], jaw_period: Optional[int] = None, teeth_period: Optional[int] = None, lips_period: Optional[int] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_bias(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_bop(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_cfo(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_cti(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_efi(close: List[float], volume: List[float], period: Optional[int] = None) -> List[float]: ...
def py_entropy(close: List[float], period: Optional[int] = None, bins: Optional[int] = None) -> List[float]: ...
def py_er(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_inertia(open: List[float], high: List[float], low: List[float], close: List[float], rvi_period: Optional[int] = None, regression_period: Optional[int] = None) -> List[float]: ...
def py_kst(close: List[float], roc1: Optional[int] = None, roc2: Optional[int] = None, roc3: Optional[int] = None, roc4: Optional[int] = None, signal_period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_long_line(open: List[float], high: List[float], low: List[float], close: List[float], lookback: Optional[int] = None) -> List[float]: ...
def py_mat_hold(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_pgo(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_psl(close: List[float], period: Optional[int] = None) -> List[float]: ...
def py_qqe(close: List[float], rsi_period: Optional[int] = None, smooth: Optional[int] = None, multiplier: Optional[float] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_rvi(open: List[float], high: List[float], low: List[float], close: List[float], period: Optional[int] = None, signal_period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_short_line(open: List[float], high: List[float], low: List[float], close: List[float], lookback: Optional[int] = None) -> List[float]: ...
def py_smi(high: List[float], low: List[float], close: List[float], period: Optional[int] = None, smooth1: Optional[int] = None, smooth2: Optional[int] = None) -> List[float]: ...
def py_squeeze(high: List[float], low: List[float], close: List[float], bb_period: Optional[int] = None, bb_std: Optional[float] = None, kc_period: Optional[int] = None, kc_atr_period: Optional[int] = None, kc_mult: Optional[float] = None) -> Tuple[List[float], List[float], List[float]]: ...
def py_ssl_channel(high: List[float], low: List[float], close: List[float], period: Optional[int] = None) -> Tuple[List[float], List[float]]: ...
def py_stc(close: List[float], fast: Optional[int] = None, slow: Optional[int] = None, cycle: Optional[int] = None) -> List[float]: ...
def py_tdfi(close: List[float], period: Optional[int] = None, smooth: Optional[int] = None) -> List[float]: ...
def py_three_inside(open: List[float], high: List[float], low: List[float], close: List[float]) -> List[float]: ...
def py_wae(close: List[float], fast: Optional[int] = None, slow: Optional[int] = None, signal: Optional[int] = None, bb_period: Optional[int] = None, multiplier: Optional[float] = None) -> Tuple[List[float], List[float]]: ...


# ==============================================================================
# Classes
# ==============================================================================

class Candle:
    """OHLCV candle data structure."""
    open: float
    high: float
    low: float
    close: float
    volume: float
    def __init__(self, open: float, high: float, low: float, close: float, volume: float) -> None: ...

class IndicatorResult:
    """Single indicator calculation result."""
    values: List[float]
    def __init__(self, values: List[float]) -> None: ...

class MultiIndicatorResult:
    """Multiple indicator calculation results."""
    results: Tuple[List[float], ...]
    def __init__(self, results: Tuple[List[float], ...]) -> None: ...

class PyHarmonicPattern:
    """Harmonic pattern recognition result."""
    pattern_type: str
    confidence: float
    points: List[Tuple[int, float]]
    def __init__(self, pattern_type: str, confidence: float, points: List[Tuple[int, float]]) -> None: ...
